language: python

dist: trusty

matrix:
  include:

# linux + python

    - os: linux
      python: 2.6
      name: ubuntu 14.04 - python@2.6
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 2.7
      name: ubuntu 14.04 - python@2.7
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.3
      name: ubuntu 14.04 - python@3.3
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.4
      name: ubuntu 14.04 - python@3.4
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.5
      name: ubuntu 14.04 - python@3.5
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.6
      name: ubuntu 14.04 - python@3.6
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.7
      name: ubuntu 14.04 - python@3.7
      dist: xenial
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.8-dev
      name: ubuntu 14.04 - python@3.8-dev
      dist: xenial
      env:
        - MATRIX_EVAL=""

  allow_failures:
    # python2.6 and python3.3 are no longer supported by opencv
    # python3.8 does not yet supports opencv
    - name: ubuntu 14.04 - python@2.6
    - name: ubuntu 14.04 - python@2.7
    - name: ubuntu 14.04 - python@3.3


before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  #- pip install -r requirements.txt
  - pip install pydicom==1.3.0
  - pip install nibabel==2.5.0
  - pip install enum34
  - pip install codecov

install:
  - python setup.py install

script:
  #- coverage run tests.py
  - exit 0

after_success:
  - codecov
