language: python

dist: trusty

matrix:
  include:

# linux + python

    - os: linux
      python: 3.5
      name: ubuntu 14.04 - python@3.5
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.6
      name: ubuntu 14.04 - python@3.6
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.7
      name: ubuntu 14.04 - python@3.7
      dist: xenial
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.8
      name: ubuntu 14.04 - python@3.8
      dist: xenial
      env:
        - MATRIX_EVAL=""

before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  - python -m pip install --upgrade pip
  - python -m pip install codecov

install:
  - python -m pip install .

script:
  #- coverage run tests.py
  - exit 0

after_success:
  - codecov
